// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdJGjWm0BTp2-KomtEgR-64s7ABRKSy2I',
    appId: '1:415835605695:web:84f80af0f4eb5167d8540a',
    messagingSenderId: '415835605695',
    projectId: 'karmait2',
    authDomain: 'karmait2.firebaseapp.com',
    storageBucket: 'karmait2.appspot.com',
    measurementId: 'G-1CF2QG0BK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHmn8UDDKCs14AMzs92MFQbCU1EC9PGF4',
    appId: '1:415835605695:android:0bc8340b64c1ed46d8540a',
    messagingSenderId: '415835605695',
    projectId: 'karmait2',
    storageBucket: 'karmait2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNImN5yVlnmdhPU9EDgNMzuLtIdrgcY64',
    appId: '1:415835605695:ios:79fec82030f21a6bd8540a',
    messagingSenderId: '415835605695',
    projectId: 'karmait2',
    storageBucket: 'karmait2.appspot.com',
    iosBundleId: 'com.example.karmait',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNImN5yVlnmdhPU9EDgNMzuLtIdrgcY64',
    appId: '1:415835605695:ios:f9c70f9c55ddca1fd8540a',
    messagingSenderId: '415835605695',
    projectId: 'karmait2',
    storageBucket: 'karmait2.appspot.com',
    iosBundleId: 'com.example.karmait.RunnerTests',
  );
}
